# Generated by Django 5.1.4 on 2024-12-19 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_thematicarea'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
                ('agency', models.CharField(max_length=100)),
                ('budget_line_item', models.CharField(max_length=100)),
                ('state_fp_budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('state_fp_release', models.DecimalField(decimal_places=2, max_digits=10)),
                ('year', models.IntegerField()),
                ('total_state_health_budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('percent_srh_budget', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StateCostImplementationPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
                ('funding_agent', models.CharField(max_length=100)),
                ('thematic_area', models.CharField(max_length=100)),
                ('data_source', models.CharField(max_length=100)),
                ('key_activities', models.TextField()),
                ('costed_in_state_plan', models.DecimalField(decimal_places=2, max_digits=10)),
                ('year', models.IntegerField()),
                ('created_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StateImplementingPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
                ('funding_agent', models.CharField(max_length=100)),
                ('thematic_area', models.CharField(max_length=100)),
                ('key_activities', models.TextField()),
                ('actual_implementation_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('year', models.IntegerField()),
                ('created_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
