# Generated by Django 5.1.4 on 2024-12-19 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_statebudget_statecostimplementationplan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyActivities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
