# Generated by Django 5.1.4 on 2024-12-19 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_keyactivities'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateFPCommodity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('funding_required', models.DecimalField(decimal_places=2, max_digits=10)),
                ('funding_commitment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fund_disbursed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('donor_agency', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('created_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
