# Generated by Django 5.1.4 on 2024-12-24 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_category_statecommoditymix'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContraceptiveStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField(unique=True)),
                ('women_receiving_contraceptive_care', models.PositiveIntegerField()),
                ('unintended_pregnancies_averted', models.PositiveIntegerField()),
                ('unplanned_births_averted', models.PositiveIntegerField()),
                ('unsafe_abortions_averted', models.PositiveIntegerField()),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
