# Generated by Django 4.2.22 on 2025-06-06 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0007_contraceptivestatistics"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChildImmunizationRegister",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("settlement", models.CharField(max_length=255)),
                ("name_of_facility", models.CharField(max_length=255)),
                ("year", models.IntegerField()),
                ("facility_name", models.CharField(max_length=255)),
                ("session_type", models.CharField(max_length=255)),
                ("session_name", models.CharField(max_length=255)),
                ("facility_type", models.CharField(max_length=50)),
                ("ward", models.CharField(max_length=255)),
                ("lga", models.CharField(max_length=255)),
                ("state", models.CharField(max_length=255)),
                ("date_of_visit", models.DateField()),
                ("client_name", models.CharField(max_length=255)),
                ("card_number", models.CharField(max_length=50)),
                ("sex", models.CharField(max_length=6)),
                ("follow_up_address", models.TextField(blank=True, null=True)),
                ("phone_number", models.CharField(max_length=20)),
                ("date_of_birth", models.DateField()),
                ("hep_b_screening_0_24_hours", models.BooleanField(default=False)),
                ("hep_b_screening_above_24_hours", models.BooleanField(default=False)),
                ("opv_0_date", models.DateField(blank=True, null=True)),
                ("bcg_date", models.DateField(blank=True, null=True)),
                ("opv_1_date", models.DateField(blank=True, null=True)),
                ("penta1_date", models.DateField(blank=True, null=True)),
                ("pcv1_date", models.DateField(blank=True, null=True)),
                ("rota_1_date", models.DateField(blank=True, null=True)),
                ("ipv_1_date", models.DateField(blank=True, null=True)),
                ("opv_2_date", models.DateField(blank=True, null=True)),
                ("penta2_date", models.DateField(blank=True, null=True)),
                ("pcv2_date", models.DateField(blank=True, null=True)),
                ("rota_2_date", models.DateField(blank=True, null=True)),
                ("opv_3_date", models.DateField(blank=True, null=True)),
                ("penta3_date", models.DateField(blank=True, null=True)),
                ("pcv3_date", models.DateField(blank=True, null=True)),
                ("rota_3_date", models.DateField(blank=True, null=True)),
                ("ipv_2_date", models.DateField(blank=True, null=True)),
                ("malaria_1_date", models.DateField(blank=True, null=True)),
                ("malaria_2_date", models.DateField(blank=True, null=True)),
                ("vitamin_a_1_date", models.DateField(blank=True, null=True)),
                ("malaria_3_date", models.DateField(blank=True, null=True)),
                ("mr_1_date", models.DateField(blank=True, null=True)),
                ("yellow_fever_date", models.DateField(blank=True, null=True)),
                ("men_a_date", models.DateField(blank=True, null=True)),
                ("mr_2_date", models.DateField(blank=True, null=True)),
                ("malaria_4_date", models.DateField(blank=True, null=True)),
                ("itn_given", models.BooleanField(default=False)),
                ("comments", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="DailyANCRegister",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.CharField(max_length=255)),
                ("lga", models.CharField(max_length=255)),
                ("ward", models.CharField(max_length=255)),
                ("facility_name", models.CharField(max_length=255)),
                ("month", models.CharField(max_length=20)),
                ("year", models.IntegerField()),
                ("date", models.DateField()),
                ("client_name", models.CharField(max_length=255)),
                ("anc_card_number", models.CharField(max_length=50)),
                ("age", models.IntegerField()),
                ("parity", models.IntegerField()),
                ("type_of_visit", models.CharField(max_length=50)),
                ("number_of_visits", models.IntegerField()),
                ("last_menstrual_period", models.DateField()),
                ("gestation_age", models.IntegerField()),
                ("weight", models.DecimalField(decimal_places=2, max_digits=5)),
                ("height", models.DecimalField(decimal_places=2, max_digits=3)),
                ("blood_pressure", models.CharField(max_length=20)),
                ("group_anc", models.BooleanField(default=False)),
                ("anc_counseling", models.TextField(blank=True, null=True)),
                ("maternal_nutrition", models.BooleanField(default=False)),
                (
                    "multiple_micronutrient_supplement",
                    models.BooleanField(default=False),
                ),
                ("maternal_mental_health", models.BooleanField(default=False)),
                ("hygiene_in_pregnancy", models.BooleanField(default=False)),
                ("gbv_fgm", models.BooleanField(default=False)),
                (
                    "early_initiation_of_breastfeeding",
                    models.BooleanField(default=False),
                ),
                ("exclusive_breastfeeding", models.BooleanField(default=False)),
                ("hiv_testing_services", models.BooleanField(default=False)),
                ("malaria_in_pregnancy", models.BooleanField(default=False)),
                ("vvf", models.BooleanField(default=False)),
                ("family_planning_postpartum_fp", models.BooleanField(default=False)),
                ("birth_registration", models.BooleanField(default=False)),
                ("hiv_self_care_kit", models.BooleanField(default=False)),
                ("hiv_testing", models.BooleanField(default=False)),
                ("hpv_kit", models.BooleanField(default=False)),
                (
                    "syphilis_testing_result",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Not Done", "Not Done"),
                            ("Negative", "Negative"),
                            ("Positive", "Positive"),
                            ("Treated", "Treated"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "hepatitis_b_result",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Not Done", "Not Done"),
                            ("Positive", "Positive"),
                            ("Negative", "Negative"),
                            ("Referred", "Referred out for treatment"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "hepatitis_c_result",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Not Done", "Not Done"),
                            ("Positive", "Positive"),
                            ("Negative", "Negative"),
                            ("Referred", "Referred out for treatment"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "haematology_test_result",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("HB/PCV", "HB/PCV (in g/dl or %)"),
                            ("Sugar", "Sugar (Gestational Diabetes)"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "urinalysis_result",
                    models.CharField(
                        blank=True,
                        choices=[("Proteins", "Proteins"), ("Sugar", "Sugar")],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "haematinics_given",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("IFAS", "Iron and Folic Acid Supplement (IFAS)"),
                            ("MMS", "Multiple Micronutrient Supplement (MMS)"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "doses_of_IPT_given",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("IPT1", "IPT 1"),
                            ("IPT2", "IPT 2"),
                            ("IPT3", "IPT 3"),
                            ("IPT4", "IPT ≥4"),
                        ],
                        max_length=5,
                        null=True,
                    ),
                ),
                ("tetanus_diphtheria", models.CharField(max_length=10)),
                ("itn_given", models.BooleanField(default=False)),
                ("associated_problems", models.TextField(blank=True, null=True)),
                ("outcome_of_visit", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="LabourDeliveryRegister",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.CharField(max_length=255)),
                ("lga", models.CharField(max_length=255)),
                ("ward", models.CharField(max_length=255)),
                ("facility_name", models.CharField(max_length=255)),
                ("month_year", models.CharField(max_length=7)),
                ("date", models.DateField()),
                ("client_name", models.CharField(max_length=255)),
                ("client_number", models.CharField(max_length=50)),
                (
                    "age_group",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("10-14", "10 - 14 years"),
                            ("15-19", "15 - 19 years"),
                            ("20-24", "20 - 24 years"),
                            ("25-35", "25 - 35 years"),
                            ("36-49", "36 - 49 years"),
                            ("50+", "≥ 50 years"),
                        ],
                        max_length=5,
                        null=True,
                    ),
                ),
                ("type_of_client", models.CharField(max_length=50)),
                (
                    "time_taken_on_decision",
                    models.CharField(
                        blank=True,
                        choices=[("<24hrs", "< 24 hours"), ("≥24hrs", "≥ 24 hours")],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("incoming_referral", models.CharField(max_length=50)),
                ("parity", models.IntegerField()),
                ("delivery_date", models.DateField()),
                ("delivery_mode", models.CharField(max_length=20)),
                (
                    "labour_monitoring",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Partograph Used", "Partograph Used"),
                            ("Labour Care Guide Use", "Labour Care Guide Use"),
                        ],
                        max_length=200,
                        null=True,
                    ),
                ),
                ("uterotonic_given", models.BooleanField(default=False)),
                ("oxytocin_given", models.BooleanField(default=False)),
                ("misoprostol_given", models.BooleanField(default=False)),
                ("heat_stable_carbetocin_given", models.BooleanField(default=False)),
                (
                    "maternal_complication",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "blood_loss_measurement_mls",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("e_motive_provided", models.BooleanField(default=False)),
                ("post_abortion_care_provided", models.BooleanField(default=False)),
                (
                    "admission_reason",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("eclampsia_mgso4_provided", models.BooleanField(default=False)),
                ("discharge_date", models.DateField(blank=True, null=True)),
                (
                    "exclusive_breastfeeding_counselled",
                    models.BooleanField(default=False),
                ),
                ("ppfp_counselled", models.BooleanField(default=False)),
                (
                    "accepted_ppfp_method",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "means_of_transport_in",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Vehicle", "Vehicle"),
                            ("Ambulance", "Ambulance"),
                            ("Others", "Others"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("mother_dead", models.BooleanField(default=False)),
                ("maternal_death_audit_conducted", models.BooleanField(default=False)),
                (
                    "maternal_death_audit_not_conducted",
                    models.BooleanField(default=False),
                ),
                ("induced_abortion", models.BooleanField(default=False)),
                ("spontaneous_abortion", models.BooleanField(default=False)),
                ("time_of_birth", models.DateTimeField(blank=True, null=True)),
                (
                    "sex_of_baby",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Male"), ("F", "Female")],
                        max_length=1,
                        null=True,
                    ),
                ),
                ("stillbirth", models.BooleanField(default=False)),
                (
                    "live_birth_weight",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("<1.0 Kg", "< 1.0 Kg"),
                            ("1.0-1.5 Kg", "1.0 - < 1.5 Kg"),
                            ("1.5-2.5 Kg", "1.5 - < 2.5 Kg"),
                            ("≥2.5 Kg", "≥ 2.5 Kg"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("still_birth", models.BooleanField(default=False)),
                ("still_birth_status", models.CharField(max_length=255)),
                (
                    "pre_term",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("<28 weeks", "< 28 weeks"),
                            ("28-32 weeks", "28 - < 32 weeks"),
                            ("32-34 weeks", "32 - < 34 weeks"),
                            ("34-37 weeks", "34 - < 37 weeks"),
                        ],
                        max_length=15,
                        null=True,
                    ),
                ),
                ("admitted_to_kmc", models.BooleanField(default=False)),
                (
                    "birth_asphyxia",
                    models.CharField(
                        blank=True,
                        choices=[("NB", "Not Breathing"), ("NC", "Not Crying")],
                        max_length=2,
                        null=True,
                    ),
                ),
                ("resuscitated_with_ambu_bag", models.BooleanField(default=False)),
                ("live_births_hiv_positive", models.BooleanField(default=False)),
                ("referral_reason", models.TextField(blank=True, null=True)),
                ("early_neonatal_death", models.BooleanField(default=False)),
                ("time_cord_clamped", models.DateTimeField(blank=True, null=True)),
                ("chx_gel_applied", models.BooleanField(default=False)),
                (
                    "skin_to_skin_care_time",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("within_1_hour", "Within 1 Hour"),
                            ("after_1_hour", "After 1 Hour"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "temperature_at_1_hour",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                (
                    "breastfeeding_initiation_time",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                "within_1_hour",
                                "Initiation of breastfeeding within 1 hour",
                            ),
                            (
                                "after_1_hour",
                                "Initiation of breastfeeding after 1 hour",
                            ),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "delivery_skilled_birth_attendant",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                "SBA: Doctor, Midwife or Nurse, MLSS-trained CHEW",
                                "SBA: Doctor, Midwife or Nurse, MLSS-trained CHEW",
                            ),
                            ("Others", "others"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "name_of_delivery_attendant",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Uterotonic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
    ]
