# Generated by Django 4.2.22 on 2025-06-06 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0008_childimmunizationregister_dailyancregister_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dailyancregister",
            name="anc_counseling",
        ),
    ]
