# Generated by Django 5.1.4 on 2025-06-07 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0009_remove_dailyancregister_anc_counseling"),
    ]

    operations = [
        migrations.AlterField(
            model_name="labourdeliveryregister",
            name="time_cord_clamped",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="labourdeliveryregister",
            name="time_of_birth",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
