# Generated by Django 5.1.4 on 2025-06-07 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0010_alter_labourdeliveryregister_time_cord_clamped_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="childimmunizationregister",
            name="bcg_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="childimmunizationregister",
            name="date_of_birth",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="childimmunizationregister",
            name="date_of_visit",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="childimmunizationregister",
            name="ipv_1_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="childimmunizationregister",
            name="ipv_2_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="childimmunizationregister",
            name="malaria_1_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="childimmunizationregister",
            name="malaria_2_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="childimmunizationregister",
            name="malaria_3_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="childimmunizationregister",
            name="malaria_4_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="childimmunizationregister",
            name="men_a_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="childimmunizationregister",
            name="mr_1_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="childimmunizationregister",
            name="mr_2_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="childimmunizationregister",
            name="opv_0_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="childimmunizationregister",
            name="opv_1_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="childimmunizationregister",
            name="opv_2_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="childimmunizationregister",
            name="opv_3_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="childimmunizationregister",
            name="pcv1_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="childimmunizationregister",
            name="pcv2_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="childimmunizationregister",
            name="pcv3_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="childimmunizationregister",
            name="penta1_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="childimmunizationregister",
            name="penta2_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="childimmunizationregister",
            name="penta3_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="childimmunizationregister",
            name="rota_1_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="childimmunizationregister",
            name="rota_2_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="childimmunizationregister",
            name="rota_3_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="childimmunizationregister",
            name="vitamin_a_1_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="childimmunizationregister",
            name="yellow_fever_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
