# Generated by Django 5.1.4 on 2025-06-08 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0011_alter_childimmunizationregister_bcg_date_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.DeleteModel(
            name="CommodityList",
        ),
        migrations.DeleteModel(
            name="ContraceptiveStatistics",
        ),
        migrations.DeleteModel(
            name="FundingAgent",
        ),
        migrations.DeleteModel(
            name="KeyActivities",
        ),
        migrations.DeleteModel(
            name="StateBudget",
        ),
        migrations.DeleteModel(
            name="StateCommodityMix",
        ),
        migrations.DeleteModel(
            name="StateCostImplementationPlan",
        ),
        migrations.DeleteModel(
            name="StateFPCommodity",
        ),
        migrations.DeleteModel(
            name="StateImplementingPartner",
        ),
        migrations.DeleteModel(
            name="ThematicArea",
        ),
    ]
