# Generated by Django 5.1.4 on 2025-06-08 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0013_childimmunizationregister_date_created_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChildImmunizationTally",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "session_type",
                    models.CharField(
                        choices=[
                            ("FIXED", "Fixed"),
                            ("OUTREACH", "Outreach"),
                            ("MOBILE", "Mobile"),
                        ],
                        max_length=8,
                    ),
                ),
                ("site_name", models.CharField(blank=True, max_length=200, null=True)),
                ("hep_b_0_24_hours", models.PositiveIntegerField(default=0)),
                ("hep_b_above_24_hours", models.PositiveIntegerField(default=0)),
                ("opv_0", models.PositiveIntegerField(default=0)),
                ("bcg", models.PositiveIntegerField(default=0)),
                ("opv_1", models.PositiveIntegerField(default=0)),
                ("penta1", models.PositiveIntegerField(default=0)),
                ("pcv1", models.PositiveIntegerField(default=0)),
                ("rota1", models.PositiveIntegerField(default=0)),
                ("ipv1", models.PositiveIntegerField(default=0)),
                ("opv2", models.PositiveIntegerField(default=0)),
                ("penta2", models.PositiveIntegerField(default=0)),
                ("pcv2", models.PositiveIntegerField(default=0)),
                ("rota2", models.PositiveIntegerField(default=0)),
                ("opv3", models.PositiveIntegerField(default=0)),
                ("penta3", models.PositiveIntegerField(default=0)),
                ("pcv3", models.PositiveIntegerField(default=0)),
                ("rota3", models.PositiveIntegerField(default=0)),
                ("ipv2", models.PositiveIntegerField(default=0)),
                ("malaria1", models.PositiveIntegerField(default=0)),
                ("malaria2", models.PositiveIntegerField(default=0)),
                ("vitamin_a_6_11", models.PositiveIntegerField(default=0)),
                ("vitamin_a_12_23", models.PositiveIntegerField(default=0)),
                ("malaria3", models.PositiveIntegerField(default=0)),
                ("mr1", models.PositiveIntegerField(default=0)),
                ("yellow_fever", models.PositiveIntegerField(default=0)),
                ("men_a", models.PositiveIntegerField(default=0)),
                ("mr2", models.PositiveIntegerField(default=0)),
                ("malaria4", models.PositiveIntegerField(default=0)),
                ("itn_given", models.PositiveIntegerField(default=0)),
                ("comments", models.TextField(blank=True, null=True)),
                ("facility_name", models.CharField(max_length=200)),
                (
                    "facility_type",
                    models.CharField(
                        choices=[("PUBLIC", "Public"), ("PRIVATE", "Private")],
                        max_length=10,
                    ),
                ),
                ("ward", models.CharField(max_length=100)),
                ("lga", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("health_officer_name", models.CharField(max_length=200)),
                ("health_officer_signature", models.CharField(max_length=200)),
                ("health_officer_date", models.DateField()),
                ("health_officer_phone", models.CharField(max_length=20)),
                ("head_of_unit_name", models.CharField(max_length=200)),
                ("head_of_unit_signature", models.CharField(max_length=200)),
                ("head_of_unit_date", models.DateField()),
                ("head_of_unit_phone", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Child Immunization Tally",
                "verbose_name_plural": "Child Immunization Tallies",
                "ordering": ["-date"],
                "unique_together": {
                    ("facility_name", "date", "session_type", "site_name")
                },
            },
        ),
    ]
